on: [push]

jobs:
  setup_awx_cli_job:
    runs-on: ubuntu-latest
    name: Validate AWX CLI installation
    steps:
      - uses: actions/checkout@v2

      - uses: actions/awx-setup-cli-action@ce926166c4dde98aacfec2dc7d9894b41db26c51

      - run: awx --version
        shell: bash
