on: [push]

jobs:
  setup_awx_cli_job:
    runs-on: ubuntu-latest
    name: Validate AWX CLI installation
    steps:
      - uses: actions/checkout@v2

      - uses: actions/awx-setup-cli-action@v1

      - run: awx --version
        shell: bash
